server:
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: banckAccount
    kafka:
      producer:
          bootstrap-servers: locahost:90092
          key-serializer: org.apache.kafka.common.serializetion.StringSerializer
          value-deserializer: org.springframework.kafka.supporte.serializer.JsonDeserializer
